# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-03-01 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('sum_up', models.IntegerField(default=0, verbose_name='点赞数')),
            ],
            options={
                'verbose_name': '博客评论父类',
                'verbose_name_plural': '博客评论父类',
                'db_table': 'comment_manage',
            },
        ),
        migrations.CreateModel(
            name='CommentManageSon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('pub_cont', models.CharField(max_length=256, verbose_name='回复内容')),
            ],
            options={
                'verbose_name': '博客评论子类',
                'verbose_name_plural': '博客评论子类',
                'db_table': 'comment_manage_son',
            },
        ),
    ]
