# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-03-02 05:10
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190301_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemanage',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='文章主体内容'),
        ),
    ]
